# Generated by Django 5.2.10 on 2026-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(choices=[('AAPL', 'Apple Inc (AAPL)'), ('MSFT', 'Microsoft (MSFT)'), ('GOOG', 'Google (GOOG)'), ('TSLA', 'Tesla (TSLA)'), ('AMZN', 'Amazon (AMZN)')], max_length=10, unique=True),
        ),
    ]
